### ISSUE TITLE
Is casbin-ex production-ready?

### ISSUE THREAD

**Issue by dbi1** [casbin/casbin-ex#3]
Hello,

very excited to see this Casbin port to Elixir, thank you for making this happen :)

I noticed some of the Casbin ports are denoted as "production ready" in the docs.

Any sense where this port stands in terms of production readiness?

Thank you!

**Comment by hsluoyz** [comment]
@ngoclinhng

**Comment by ngoclinhng** [comment]
Yes, it definitely is (even though _it is still far from completed_). We have been using it in production for [taskbook](https://app.taskbook.io/) since the beginning and have no issues with it.

**Comment by ngoclinhng** [comment]
My apologies for the late reply to you both @hsluoyz @dbi1

**Comment by hsluoyz** [comment]
@ngoclinhng great! Thanks for the reply :)
